apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5001"
  JWT_EXPIRES_IN: "1d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5002"
  JWT_EXPIRES_IN: "1d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5003"
  JWT_EXPIRES_IN: "1d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5004"
  JWT_EXPIRES_IN: "1d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5005"
  JWT_EXPIRES_IN: "1d"