{{- range $name, $service := .Values.services }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: {{ $service.name }}

  template:
    metadata:
      labels:
        app: {{ $service.name }}

    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: IfNotPresent

          {{- if eq $service.name "frontend-service" }}
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=768"
          {{- end }}

          ports:
            - containerPort: {{ $service.port }}

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          {{- if or $service.configMap $service.secret }}
          envFrom:

            {{- if $service.configMap }}
            - configMapRef:
                name: {{ $service.configMap }}
            {{- end }}

            {{- if $service.secret }}
            - secretRef:
                name: {{ $service.secret }}
            {{- end }}

          {{- end }}

---

{{- end }}