apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: ""
  JWT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: ""
  JWT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: delivery-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: ""
  JWT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: ""
  STRIPE_SECRET_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://pasupuletichiranjeevi2005_db_user:wvdHCl3JfTSTdazz@sky-dash.kd1zfuo.mongodb.net/?retryWrites=true&w=majority&appName=sky-dash
  JWT_SECRET: your_jwt_secret