apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: delivery-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}