{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}
      targetPort: {{ $service.port }}
---
{{- end }}