name: Auth Service CI/CD

on:
  push:
    paths:
      - "backend/auth-service/**"
      - ".github/workflows/auth-service.yml"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t chirudevops46/auth-service:${{ github.sha }} ./backend/auth-service

      - name: Push Docker image
        run: docker push chirudevops46/auth-service:${{ github.sha }}

      - name: Create temporary Helm secrets
        shell: powershell
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          @"
          secrets:
            mongoUri: "$env:MONGO_URI"
            jwtSecret: "$env:JWT_SECRET"
            stripeSecretKey: "$env:STRIPE_SECRET_KEY"
          "@ | Set-Content helm/skydash/ci-secrets-values.yaml

      - name: Deploy auth-service to Minikube
        shell: powershell
        run: |
          helm upgrade skydash ./helm/skydash `
            -n skydash `
            -f ./helm/skydash/ci-secrets-values.yaml `
            --server-side=false `
            --set services.auth.image.repository=chirudevops46/auth-service `
            --set services.auth.image.tag=${{ github.sha }}

      - name: Verify auth-service rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/auth-service -n skydash

      - name: Remove temporary secrets file
        if: always()
        shell: powershell
        run: |
          Remove-Item helm/skydash/ci-secrets-values.yaml -Force -ErrorAction SilentlyContinue